name: Test the local build on ARM64

on:
  push:
    branches:
      - gh_runner_workflow_woa

jobs:
  build-arm64:
    runs-on: [self-hosted, Windows, ARM64]
    name: Build on local ARM64 runner

    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Print system info
        shell: cmd
        run: |
          echo Running on %COMPUTERNAME%
          echo Architecture: %PROCESSOR_ARCHITECTURE%

      - name: Environment setup and run the build
        shell: cmd
        run: |
          cmd.exe /c C:/wenv/arm64/activate.bat bash -c "echo 'Installing Conan...';python -m pip install conan;echo 'Detecting Conan profile...';conan profile detect;echo 'Writing global.conf...';echo 'tools.microsoft.bash:path=c:/wenv/msys2/msys64/usr/bin/bash.exe' > global.conf; echo 'tools.microsoft.bash:subsystem=msys2' >> global.conf;conan config install global.conf; mkdir -p build && cd build; cmake -A arm64 -S ../ -B .; cmake --build . --config Release"